### ISSUE TITLE
Desarrollo de las principales funciones

### ISSUE THREAD

**Issue by lquintanac** [aigora/twIE_2021-laberinto#6]
Debéis implementar las principales funciones del programa.
Esta implementación puede tener cambios en la versión definitiva. Aún no es necesario que realice todas las funcionalidades previstas.
Se recomienda el uso de librerías propias para alojar estas funciones.

**Comment by Jorgebpinedo** [comment]
Es posible que el menu principal este silenciado. 
Para que funcione todo correctamente silenciar el archivo "Main.c" y desilenciar "Menu principal.c"
